        java BruteForceDES 1 20 >> Results.txt
        java BruteForceDES 1 20 >> Results.txt
        java BruteForceDES 1 20 >> Results.txt
        java BruteForceDES 2 21 >> Results.txt
        java BruteForceDES 2 21 >> Results.txt
        java BruteForceDES 2 22 >> Results.txt
        java BruteForceDES 4 22 >> Results.txt
        java BruteForceDES 4 22 >> Results.txt
        java BruteForceDES 4 22 >> Results.txt
        java BruteForceDES 8 23 >> Results.txt
        java BruteForceDES 8 23 >> Results.txt
        java BruteForceDES 8 23 >> Results.txt
        java BruteForceDES 16 24 >> Results.txt
        java BruteForceDES 16 24 >> Results.txt
        java BruteForceDES 16 24 >> Results.txt